name: Lint Codebase

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  NODE_VERSION: '20'

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: ⤵️ Install Node Dependencies
        run: |
          if [[ -f "Makefile" ]]; then
            MAKEFILE_LIST="$(make -rpn | sed -n -e '/^$/ { n ; /^[^ .#][^ ]*:/ { s/:.*$// ; p ; } ; }')"
          fi

          if [[ -f "Makefile" ]] && [[ " ${MAKEFILE_LIST[*]} " =~ setup-npm ]]; then
            echo "installing node dependencies using Makefile...";
            make setup-npm;
          elif [[ -f "package-lock.json" ]]; then
            echo "installing node dependencies using pipeline";
            npm ci;
          else
            red="\e[31m";
            end_color="\e[0m";
            echo "${red}lockfile missing - can't install dependencies${end_color}";
            exit 9;
          fi
      - name: 🚀 Run Linters
        id: super-linter
        uses: super-linter/super-linter/slim@v7.1.0
        env:
          DEFAULT_BRANCH: master
          FILTER_REGEX_EXCLUDE: dist/**/*|LICENSE|README.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CHECKOV: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
